services:
  # Backend service
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortener
      - REDIS_URL=redis://redis:6379
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=50
      - RATE_LIMIT_MESSAGE="Too many URL shortening requests, please try again later"
      - BASE_URL=http://localhost:8000
      - JWT_SECRET=your-secret-key
      - PORT=8000

  # MongoDB service
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BASE_URL=http://localhost:8000

volumes:
  mongo_data:
